### ISSUE TITLE
Avoid running System Tests

### ISSUE THREAD

**Issue by shayani** [willbryant/parallel_rspec#10]
Thanks for this amazing gem. 

Is there a way to run all tests, except for the system tests (under `spec/system` folder)?

**Comment by shayani** [comment]
I assumed it would not work, since I use the flag `--fail-fast` and it is ignored; but I added the `--exclude-pattern "**/system/**"` flag now and it worked.

Any idea why `--fail-fast` is ignored?

**Comment by willbryant** [comment]
Cool! I'm not sure how `--fail-fast` should behave when things are running in parallel, but feel free to open an issue with your expected behavior.
